category: Exceptions
description: ratel-wai notifies Honeybadger about exceptions via a WAI middleware.
extra-source-files:
- CHANGELOG.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: tfausak/ratel-wai
library:
  dependencies:
  - base >=4.8 && <4.11
  - bytestring ==0.10.*
  - case-insensitive ==1.2.*
  - containers ==0.5.*
  - http-client >=0.4.30 && <0.6
  - ratel ==0.3.*
  - wai ==3.2.*
  source-dirs: library
license: MIT
maintainer: Taylor Fausak
name: ratel-wai
synopsis: Notify Honeybadger about exceptions via a WAI middleware.
version: '0.2.0'
